### ISSUE TITLE
The paper site is down

### ISSUE THREAD

**Issue by InCogNiTo124** [endo-yuki-t/Animating-Landscape#3]
Hello,

the [site](http://www.cgg.cs.tsukuba.ac.jp/~endo/projects/AnimatingLandscape/) that's referenced by the paper is inaccesable anymore.

**Comment by yshhrknmr** [comment]
Thanks for your notification. We are now rebuilding our laboratory server, and the project page will be accessible again very soon.

**Comment by yshhrknmr** [comment]
The project page is accessible now. http://www.cgg.cs.tsukuba.ac.jp/~endo/projects/AnimatingLandscape/
